/*
Account Management Service API

Testing AppServicesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package accountmgmtclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_accountmgmtclient_AppServicesApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test AppServicesApiService ApiAccountsMgmtV1AccessTokenPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AppServicesApi.ApiAccountsMgmtV1AccessTokenPost(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AppServicesApiService ApiAccountsMgmtV1CurrentAccountGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AppServicesApi.ApiAccountsMgmtV1CurrentAccountGet(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AppServicesApiService ApiAccountsMgmtV1OrganizationsOrgIdQuotaCostGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var orgId string

        resp, httpRes, err := apiClient.AppServicesApi.ApiAccountsMgmtV1OrganizationsOrgIdQuotaCostGet(context.Background(), orgId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AppServicesApiService ApiAuthorizationsV1SelfTermsReviewPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AppServicesApi.ApiAuthorizationsV1SelfTermsReviewPost(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
