/*
 * Kafka Management API
 *
 * Kafka Management API is a REST API to manage Kafka instances
 *
 * API version: 1.16.0
 * Contact: rhosak-support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkamgmtclient

import (
	"encoding/json"
)

// EnterpriseClusterFleetshardParameters Enterprise Cluster fleetshard parameters object
type EnterpriseClusterFleetshardParameters struct {
	// Enterprise Cluster fleetshard parameters array
	FleetshardParameters *[]FleetshardParameter `json:"fleetshard_parameters,omitempty"`
}

// NewEnterpriseClusterFleetshardParameters instantiates a new EnterpriseClusterFleetshardParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnterpriseClusterFleetshardParameters() *EnterpriseClusterFleetshardParameters {
	this := EnterpriseClusterFleetshardParameters{}
	return &this
}

// NewEnterpriseClusterFleetshardParametersWithDefaults instantiates a new EnterpriseClusterFleetshardParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnterpriseClusterFleetshardParametersWithDefaults() *EnterpriseClusterFleetshardParameters {
	this := EnterpriseClusterFleetshardParameters{}
	return &this
}

// GetFleetshardParameters returns the FleetshardParameters field value if set, zero value otherwise.
func (o *EnterpriseClusterFleetshardParameters) GetFleetshardParameters() []FleetshardParameter {
	if o == nil || o.FleetshardParameters == nil {
		var ret []FleetshardParameter
		return ret
	}
	return *o.FleetshardParameters
}

// GetFleetshardParametersOk returns a tuple with the FleetshardParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseClusterFleetshardParameters) GetFleetshardParametersOk() (*[]FleetshardParameter, bool) {
	if o == nil || o.FleetshardParameters == nil {
		return nil, false
	}
	return o.FleetshardParameters, true
}

// HasFleetshardParameters returns a boolean if a field has been set.
func (o *EnterpriseClusterFleetshardParameters) HasFleetshardParameters() bool {
	if o != nil && o.FleetshardParameters != nil {
		return true
	}

	return false
}

// SetFleetshardParameters gets a reference to the given []FleetshardParameter and assigns it to the FleetshardParameters field.
func (o *EnterpriseClusterFleetshardParameters) SetFleetshardParameters(v []FleetshardParameter) {
	o.FleetshardParameters = &v
}

func (o EnterpriseClusterFleetshardParameters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FleetshardParameters != nil {
		toSerialize["fleetshard_parameters"] = o.FleetshardParameters
	}
	return json.Marshal(toSerialize)
}

type NullableEnterpriseClusterFleetshardParameters struct {
	value *EnterpriseClusterFleetshardParameters
	isSet bool
}

func (v NullableEnterpriseClusterFleetshardParameters) Get() *EnterpriseClusterFleetshardParameters {
	return v.value
}

func (v *NullableEnterpriseClusterFleetshardParameters) Set(val *EnterpriseClusterFleetshardParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableEnterpriseClusterFleetshardParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableEnterpriseClusterFleetshardParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnterpriseClusterFleetshardParameters(val *EnterpriseClusterFleetshardParameters) *NullableEnterpriseClusterFleetshardParameters {
	return &NullableEnterpriseClusterFleetshardParameters{value: val, isSet: true}
}

func (v NullableEnterpriseClusterFleetshardParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnterpriseClusterFleetshardParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


