/*
Red Hat Openshift SmartEvents Fleet Manager V2

Testing BridgesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package smarteventsmgmtclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_smarteventsmgmtclient_BridgesApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test BridgesApiService BridgesAPICreateBridge", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.BridgesApi.BridgesAPICreateBridge(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test BridgesApiService BridgesAPIDeleteBridge", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bridgeId string

        resp, httpRes, err := apiClient.BridgesApi.BridgesAPIDeleteBridge(context.Background(), bridgeId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test BridgesApiService BridgesAPIGetBridge", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bridgeId string

        resp, httpRes, err := apiClient.BridgesApi.BridgesAPIGetBridge(context.Background(), bridgeId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test BridgesApiService BridgesAPIGetBridges", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.BridgesApi.BridgesAPIGetBridges(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
