/*
Red Hat Openshift SmartEvents Fleet Manager V2

Testing CloudProvidersApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package smarteventsmgmtclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_smarteventsmgmtclient_CloudProvidersApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test CloudProvidersApiService CloudProviderAPIGetCloudProvider", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var id string

        resp, httpRes, err := apiClient.CloudProvidersApi.CloudProviderAPIGetCloudProvider(context.Background(), id).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CloudProvidersApiService CloudProviderAPIListCloudProviderRegions", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var id string

        resp, httpRes, err := apiClient.CloudProvidersApi.CloudProviderAPIListCloudProviderRegions(context.Background(), id).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CloudProvidersApiService CloudProviderAPIListCloudProviders", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.CloudProvidersApi.CloudProviderAPIListCloudProviders(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
