"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.enterprise_cluster_registration_response_all_of import EnterpriseClusterRegistrationResponseAllOf


class TestEnterpriseClusterRegistrationResponseAllOf(unittest.TestCase):
    """EnterpriseClusterRegistrationResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseClusterRegistrationResponseAllOf(self):
        """Test EnterpriseClusterRegistrationResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseClusterRegistrationResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
