"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.15.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.enterprise_cluster_all_of_capacity_information import EnterpriseClusterAllOfCapacityInformation
from rhoas_kafka_mgmt_sdk.model.supported_kafka_instance_types_list import SupportedKafkaInstanceTypesList
globals()['EnterpriseClusterAllOfCapacityInformation'] = EnterpriseClusterAllOfCapacityInformation
globals()['SupportedKafkaInstanceTypesList'] = SupportedKafkaInstanceTypesList
from rhoas_kafka_mgmt_sdk.model.enterprise_cluster_all_of import EnterpriseClusterAllOf


class TestEnterpriseClusterAllOf(unittest.TestCase):
    """EnterpriseClusterAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseClusterAllOf(self):
        """Test EnterpriseClusterAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseClusterAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
