"""
    Kafka Management API

    Kafka Management API is a REST API to manage Kafka instances  # noqa: E501

    The version of the OpenAPI document: 1.15.0
    Contact: rhosak-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_kafka_mgmt_sdk
from rhoas_kafka_mgmt_sdk.model.supported_kafka_billing_model import SupportedKafkaBillingModel


class TestSupportedKafkaBillingModel(unittest.TestCase):
    """SupportedKafkaBillingModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedKafkaBillingModel(self):
        """Test SupportedKafkaBillingModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupportedKafkaBillingModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
