"""
    Red Hat Openshift SmartEvents Fleet Manager V2

    The API exposed by the fleet manager of the SmartEvents service.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: openbridge-dev@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_smart_events_mgmt_sdk
from rhoas_smart_events_mgmt_sdk.model.connector_request import ConnectorRequest


class TestConnectorRequest(unittest.TestCase):
    """ConnectorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorRequest(self):
        """Test ConnectorRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
