"""
    Red Hat Openshift SmartEvents Fleet Manager V2

    The API exposed by the fleet manager of the SmartEvents service.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: openbridge-dev@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_smart_events_mgmt_sdk
from rhoas_smart_events_mgmt_sdk.model.source_connector_response import SourceConnectorResponse
globals()['SourceConnectorResponse'] = SourceConnectorResponse
from rhoas_smart_events_mgmt_sdk.model.source_connector_list_response import SourceConnectorListResponse


class TestSourceConnectorListResponse(unittest.TestCase):
    """SourceConnectorListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceConnectorListResponse(self):
        """Test SourceConnectorListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceConnectorListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
