"""
    Service Registry API

    Service Registry Instance API  NOTE: This API cannot be called directly from the portal.  # noqa: E501

    The version of the OpenAPI document: 2.2.5.Final
    Contact: apicurio@lists.jboss.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import rhoas_registry_instance_sdk
from rhoas_registry_instance_sdk.api.artifact_rules_api import ArtifactRulesApi  # noqa: E501


class TestArtifactRulesApi(unittest.TestCase):
    """ArtifactRulesApi unit test stubs"""

    def setUp(self):
        self.api = ArtifactRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_artifact_rule(self):
        """Test case for create_artifact_rule

        Create artifact rule  # noqa: E501
        """
        pass

    def test_delete_artifact_rule(self):
        """Test case for delete_artifact_rule

        Delete artifact rule  # noqa: E501
        """
        pass

    def test_delete_artifact_rules(self):
        """Test case for delete_artifact_rules

        Delete artifact rules  # noqa: E501
        """
        pass

    def test_get_artifact_rule_config(self):
        """Test case for get_artifact_rule_config

        Get artifact rule configuration  # noqa: E501
        """
        pass

    def test_list_artifact_rules(self):
        """Test case for list_artifact_rules

        List artifact rules  # noqa: E501
        """
        pass

    def test_test_update_artifact(self):
        """Test case for test_update_artifact

        Test update artifact  # noqa: E501
        """
        pass

    def test_update_artifact_rule_config(self):
        """Test case for update_artifact_rule_config

        Update artifact rule configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
