"""
    Service Registry API

    Service Registry Instance API  NOTE: This API cannot be called directly from the portal.  # noqa: E501

    The version of the OpenAPI document: 2.2.5.Final
    Contact: apicurio@lists.jboss.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_registry_instance_sdk
from rhoas_registry_instance_sdk.model.error import Error
from rhoas_registry_instance_sdk.model.rule_violation_cause import RuleViolationCause
from rhoas_registry_instance_sdk.model.rule_violation_error_all_of import RuleViolationErrorAllOf
globals()['Error'] = Error
globals()['RuleViolationCause'] = RuleViolationCause
globals()['RuleViolationErrorAllOf'] = RuleViolationErrorAllOf
from rhoas_registry_instance_sdk.model.rule_violation_error import RuleViolationError


class TestRuleViolationError(unittest.TestCase):
    """RuleViolationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleViolationError(self):
        """Test RuleViolationError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuleViolationError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
