"""
    Service Registry API

    Service Registry Instance API  NOTE: This API cannot be called directly from the portal.  # noqa: E501

    The version of the OpenAPI document: 2.2.5.Final
    Contact: apicurio@lists.jboss.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_registry_instance_sdk
from rhoas_registry_instance_sdk.model.update_configuration_property import UpdateConfigurationProperty


class TestUpdateConfigurationProperty(unittest.TestCase):
    """UpdateConfigurationProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateConfigurationProperty(self):
        """Test UpdateConfigurationProperty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateConfigurationProperty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
