/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// CloudResource struct for CloudResource
type CloudResource struct {
	Href *string `json:"href,omitempty"`
	Id *string `json:"id,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Active *bool `json:"active,omitempty"`
	Category *string `json:"category,omitempty"`
	CategoryPretty *string `json:"category_pretty,omitempty"`
	CloudProvider *string `json:"cloud_provider,omitempty"`
	CpuCores *int32 `json:"cpu_cores,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	GenericName *string `json:"generic_name,omitempty"`
	Memory *int64 `json:"memory,omitempty"`
	MemoryPretty *string `json:"memory_pretty,omitempty"`
	NamePretty *string `json:"name_pretty,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
	SizePretty *string `json:"size_pretty,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewCloudResource instantiates a new CloudResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudResource() *CloudResource {
	this := CloudResource{}
	var active bool = true
	this.Active = &active
	return &this
}

// NewCloudResourceWithDefaults instantiates a new CloudResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudResourceWithDefaults() *CloudResource {
	this := CloudResource{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *CloudResource) GetHref() string {
	if o == nil || isNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetHrefOk() (*string, bool) {
	if o == nil || isNil(o.Href) {
    return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *CloudResource) HasHref() bool {
	if o != nil && !isNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *CloudResource) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CloudResource) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CloudResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CloudResource) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CloudResource) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
    return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CloudResource) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CloudResource) SetKind(v string) {
	o.Kind = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CloudResource) GetActive() bool {
	if o == nil || isNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetActiveOk() (*bool, bool) {
	if o == nil || isNil(o.Active) {
    return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CloudResource) HasActive() bool {
	if o != nil && !isNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CloudResource) SetActive(v bool) {
	o.Active = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *CloudResource) GetCategory() string {
	if o == nil || isNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetCategoryOk() (*string, bool) {
	if o == nil || isNil(o.Category) {
    return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *CloudResource) HasCategory() bool {
	if o != nil && !isNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *CloudResource) SetCategory(v string) {
	o.Category = &v
}

// GetCategoryPretty returns the CategoryPretty field value if set, zero value otherwise.
func (o *CloudResource) GetCategoryPretty() string {
	if o == nil || isNil(o.CategoryPretty) {
		var ret string
		return ret
	}
	return *o.CategoryPretty
}

// GetCategoryPrettyOk returns a tuple with the CategoryPretty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetCategoryPrettyOk() (*string, bool) {
	if o == nil || isNil(o.CategoryPretty) {
    return nil, false
	}
	return o.CategoryPretty, true
}

// HasCategoryPretty returns a boolean if a field has been set.
func (o *CloudResource) HasCategoryPretty() bool {
	if o != nil && !isNil(o.CategoryPretty) {
		return true
	}

	return false
}

// SetCategoryPretty gets a reference to the given string and assigns it to the CategoryPretty field.
func (o *CloudResource) SetCategoryPretty(v string) {
	o.CategoryPretty = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *CloudResource) GetCloudProvider() string {
	if o == nil || isNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetCloudProviderOk() (*string, bool) {
	if o == nil || isNil(o.CloudProvider) {
    return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *CloudResource) HasCloudProvider() bool {
	if o != nil && !isNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *CloudResource) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCpuCores returns the CpuCores field value if set, zero value otherwise.
func (o *CloudResource) GetCpuCores() int32 {
	if o == nil || isNil(o.CpuCores) {
		var ret int32
		return ret
	}
	return *o.CpuCores
}

// GetCpuCoresOk returns a tuple with the CpuCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetCpuCoresOk() (*int32, bool) {
	if o == nil || isNil(o.CpuCores) {
    return nil, false
	}
	return o.CpuCores, true
}

// HasCpuCores returns a boolean if a field has been set.
func (o *CloudResource) HasCpuCores() bool {
	if o != nil && !isNil(o.CpuCores) {
		return true
	}

	return false
}

// SetCpuCores gets a reference to the given int32 and assigns it to the CpuCores field.
func (o *CloudResource) SetCpuCores(v int32) {
	o.CpuCores = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CloudResource) GetCreatedAt() time.Time {
	if o == nil || isNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CloudResource) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CloudResource) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetGenericName returns the GenericName field value if set, zero value otherwise.
func (o *CloudResource) GetGenericName() string {
	if o == nil || isNil(o.GenericName) {
		var ret string
		return ret
	}
	return *o.GenericName
}

// GetGenericNameOk returns a tuple with the GenericName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetGenericNameOk() (*string, bool) {
	if o == nil || isNil(o.GenericName) {
    return nil, false
	}
	return o.GenericName, true
}

// HasGenericName returns a boolean if a field has been set.
func (o *CloudResource) HasGenericName() bool {
	if o != nil && !isNil(o.GenericName) {
		return true
	}

	return false
}

// SetGenericName gets a reference to the given string and assigns it to the GenericName field.
func (o *CloudResource) SetGenericName(v string) {
	o.GenericName = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *CloudResource) GetMemory() int64 {
	if o == nil || isNil(o.Memory) {
		var ret int64
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetMemoryOk() (*int64, bool) {
	if o == nil || isNil(o.Memory) {
    return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *CloudResource) HasMemory() bool {
	if o != nil && !isNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int64 and assigns it to the Memory field.
func (o *CloudResource) SetMemory(v int64) {
	o.Memory = &v
}

// GetMemoryPretty returns the MemoryPretty field value if set, zero value otherwise.
func (o *CloudResource) GetMemoryPretty() string {
	if o == nil || isNil(o.MemoryPretty) {
		var ret string
		return ret
	}
	return *o.MemoryPretty
}

// GetMemoryPrettyOk returns a tuple with the MemoryPretty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetMemoryPrettyOk() (*string, bool) {
	if o == nil || isNil(o.MemoryPretty) {
    return nil, false
	}
	return o.MemoryPretty, true
}

// HasMemoryPretty returns a boolean if a field has been set.
func (o *CloudResource) HasMemoryPretty() bool {
	if o != nil && !isNil(o.MemoryPretty) {
		return true
	}

	return false
}

// SetMemoryPretty gets a reference to the given string and assigns it to the MemoryPretty field.
func (o *CloudResource) SetMemoryPretty(v string) {
	o.MemoryPretty = &v
}

// GetNamePretty returns the NamePretty field value if set, zero value otherwise.
func (o *CloudResource) GetNamePretty() string {
	if o == nil || isNil(o.NamePretty) {
		var ret string
		return ret
	}
	return *o.NamePretty
}

// GetNamePrettyOk returns a tuple with the NamePretty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetNamePrettyOk() (*string, bool) {
	if o == nil || isNil(o.NamePretty) {
    return nil, false
	}
	return o.NamePretty, true
}

// HasNamePretty returns a boolean if a field has been set.
func (o *CloudResource) HasNamePretty() bool {
	if o != nil && !isNil(o.NamePretty) {
		return true
	}

	return false
}

// SetNamePretty gets a reference to the given string and assigns it to the NamePretty field.
func (o *CloudResource) SetNamePretty(v string) {
	o.NamePretty = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *CloudResource) GetResourceType() string {
	if o == nil || isNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetResourceTypeOk() (*string, bool) {
	if o == nil || isNil(o.ResourceType) {
    return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *CloudResource) HasResourceType() bool {
	if o != nil && !isNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *CloudResource) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetSizePretty returns the SizePretty field value if set, zero value otherwise.
func (o *CloudResource) GetSizePretty() string {
	if o == nil || isNil(o.SizePretty) {
		var ret string
		return ret
	}
	return *o.SizePretty
}

// GetSizePrettyOk returns a tuple with the SizePretty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetSizePrettyOk() (*string, bool) {
	if o == nil || isNil(o.SizePretty) {
    return nil, false
	}
	return o.SizePretty, true
}

// HasSizePretty returns a boolean if a field has been set.
func (o *CloudResource) HasSizePretty() bool {
	if o != nil && !isNil(o.SizePretty) {
		return true
	}

	return false
}

// SetSizePretty gets a reference to the given string and assigns it to the SizePretty field.
func (o *CloudResource) SetSizePretty(v string) {
	o.SizePretty = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CloudResource) GetUpdatedAt() time.Time {
	if o == nil || isNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResource) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CloudResource) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *CloudResource) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o CloudResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !isNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !isNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !isNil(o.CategoryPretty) {
		toSerialize["category_pretty"] = o.CategoryPretty
	}
	if !isNil(o.CloudProvider) {
		toSerialize["cloud_provider"] = o.CloudProvider
	}
	if !isNil(o.CpuCores) {
		toSerialize["cpu_cores"] = o.CpuCores
	}
	if !isNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !isNil(o.GenericName) {
		toSerialize["generic_name"] = o.GenericName
	}
	if !isNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !isNil(o.MemoryPretty) {
		toSerialize["memory_pretty"] = o.MemoryPretty
	}
	if !isNil(o.NamePretty) {
		toSerialize["name_pretty"] = o.NamePretty
	}
	if !isNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	if !isNil(o.SizePretty) {
		toSerialize["size_pretty"] = o.SizePretty
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableCloudResource struct {
	value *CloudResource
	isSet bool
}

func (v NullableCloudResource) Get() *CloudResource {
	return v.value
}

func (v *NullableCloudResource) Set(val *CloudResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudResource(val *CloudResource) *NullableCloudResource {
	return &NullableCloudResource{value: val, isSet: true}
}

func (v NullableCloudResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


