/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// ConsumedQuotaAllOf struct for ConsumedQuotaAllOf
type ConsumedQuotaAllOf struct {
	AvailabilityZoneType *string `json:"availability_zone_type,omitempty"`
	BillingModel *string `json:"billing_model,omitempty"`
	Byoc bool `json:"byoc"`
	CloudProviderId *string `json:"cloud_provider_id,omitempty"`
	Count int32 `json:"count"`
	OrganizationId *string `json:"organization_id,omitempty"`
	PlanId *string `json:"plan_id,omitempty"`
	ResourceName *string `json:"resource_name,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewConsumedQuotaAllOf instantiates a new ConsumedQuotaAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumedQuotaAllOf(byoc bool, count int32) *ConsumedQuotaAllOf {
	this := ConsumedQuotaAllOf{}
	this.Byoc = byoc
	this.Count = count
	return &this
}

// NewConsumedQuotaAllOfWithDefaults instantiates a new ConsumedQuotaAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumedQuotaAllOfWithDefaults() *ConsumedQuotaAllOf {
	this := ConsumedQuotaAllOf{}
	return &this
}

// GetAvailabilityZoneType returns the AvailabilityZoneType field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetAvailabilityZoneType() string {
	if o == nil || isNil(o.AvailabilityZoneType) {
		var ret string
		return ret
	}
	return *o.AvailabilityZoneType
}

// GetAvailabilityZoneTypeOk returns a tuple with the AvailabilityZoneType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetAvailabilityZoneTypeOk() (*string, bool) {
	if o == nil || isNil(o.AvailabilityZoneType) {
    return nil, false
	}
	return o.AvailabilityZoneType, true
}

// HasAvailabilityZoneType returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasAvailabilityZoneType() bool {
	if o != nil && !isNil(o.AvailabilityZoneType) {
		return true
	}

	return false
}

// SetAvailabilityZoneType gets a reference to the given string and assigns it to the AvailabilityZoneType field.
func (o *ConsumedQuotaAllOf) SetAvailabilityZoneType(v string) {
	o.AvailabilityZoneType = &v
}

// GetBillingModel returns the BillingModel field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetBillingModel() string {
	if o == nil || isNil(o.BillingModel) {
		var ret string
		return ret
	}
	return *o.BillingModel
}

// GetBillingModelOk returns a tuple with the BillingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetBillingModelOk() (*string, bool) {
	if o == nil || isNil(o.BillingModel) {
    return nil, false
	}
	return o.BillingModel, true
}

// HasBillingModel returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasBillingModel() bool {
	if o != nil && !isNil(o.BillingModel) {
		return true
	}

	return false
}

// SetBillingModel gets a reference to the given string and assigns it to the BillingModel field.
func (o *ConsumedQuotaAllOf) SetBillingModel(v string) {
	o.BillingModel = &v
}

// GetByoc returns the Byoc field value
func (o *ConsumedQuotaAllOf) GetByoc() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Byoc
}

// GetByocOk returns a tuple with the Byoc field value
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetByocOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Byoc, true
}

// SetByoc sets field value
func (o *ConsumedQuotaAllOf) SetByoc(v bool) {
	o.Byoc = v
}

// GetCloudProviderId returns the CloudProviderId field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetCloudProviderId() string {
	if o == nil || isNil(o.CloudProviderId) {
		var ret string
		return ret
	}
	return *o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetCloudProviderIdOk() (*string, bool) {
	if o == nil || isNil(o.CloudProviderId) {
    return nil, false
	}
	return o.CloudProviderId, true
}

// HasCloudProviderId returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasCloudProviderId() bool {
	if o != nil && !isNil(o.CloudProviderId) {
		return true
	}

	return false
}

// SetCloudProviderId gets a reference to the given string and assigns it to the CloudProviderId field.
func (o *ConsumedQuotaAllOf) SetCloudProviderId(v string) {
	o.CloudProviderId = &v
}

// GetCount returns the Count field value
func (o *ConsumedQuotaAllOf) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetCountOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ConsumedQuotaAllOf) SetCount(v int32) {
	o.Count = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetOrganizationId() string {
	if o == nil || isNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetOrganizationIdOk() (*string, bool) {
	if o == nil || isNil(o.OrganizationId) {
    return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasOrganizationId() bool {
	if o != nil && !isNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *ConsumedQuotaAllOf) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetPlanId() string {
	if o == nil || isNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetPlanIdOk() (*string, bool) {
	if o == nil || isNil(o.PlanId) {
    return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasPlanId() bool {
	if o != nil && !isNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *ConsumedQuotaAllOf) SetPlanId(v string) {
	o.PlanId = &v
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetResourceName() string {
	if o == nil || isNil(o.ResourceName) {
		var ret string
		return ret
	}
	return *o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetResourceNameOk() (*string, bool) {
	if o == nil || isNil(o.ResourceName) {
    return nil, false
	}
	return o.ResourceName, true
}

// HasResourceName returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasResourceName() bool {
	if o != nil && !isNil(o.ResourceName) {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given string and assigns it to the ResourceName field.
func (o *ConsumedQuotaAllOf) SetResourceName(v string) {
	o.ResourceName = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetResourceType() string {
	if o == nil || isNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetResourceTypeOk() (*string, bool) {
	if o == nil || isNil(o.ResourceType) {
    return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasResourceType() bool {
	if o != nil && !isNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *ConsumedQuotaAllOf) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ConsumedQuotaAllOf) GetVersion() string {
	if o == nil || isNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaAllOf) GetVersionOk() (*string, bool) {
	if o == nil || isNil(o.Version) {
    return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ConsumedQuotaAllOf) HasVersion() bool {
	if o != nil && !isNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ConsumedQuotaAllOf) SetVersion(v string) {
	o.Version = &v
}

func (o ConsumedQuotaAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AvailabilityZoneType) {
		toSerialize["availability_zone_type"] = o.AvailabilityZoneType
	}
	if !isNil(o.BillingModel) {
		toSerialize["billing_model"] = o.BillingModel
	}
	if true {
		toSerialize["byoc"] = o.Byoc
	}
	if !isNil(o.CloudProviderId) {
		toSerialize["cloud_provider_id"] = o.CloudProviderId
	}
	if true {
		toSerialize["count"] = o.Count
	}
	if !isNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !isNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !isNil(o.ResourceName) {
		toSerialize["resource_name"] = o.ResourceName
	}
	if !isNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	if !isNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableConsumedQuotaAllOf struct {
	value *ConsumedQuotaAllOf
	isSet bool
}

func (v NullableConsumedQuotaAllOf) Get() *ConsumedQuotaAllOf {
	return v.value
}

func (v *NullableConsumedQuotaAllOf) Set(val *ConsumedQuotaAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumedQuotaAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumedQuotaAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumedQuotaAllOf(val *ConsumedQuotaAllOf) *NullableConsumedQuotaAllOf {
	return &NullableConsumedQuotaAllOf{value: val, isSet: true}
}

func (v NullableConsumedQuotaAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumedQuotaAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


