/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// DeletedSubscription struct for DeletedSubscription
type DeletedSubscription struct {
	Href *string `json:"href,omitempty"`
	Id *string `json:"id,omitempty"`
	Kind *string `json:"kind,omitempty"`
	// If set, the date the subscription expires based on the billing model
	BillingExpirationDate *time.Time `json:"billing_expiration_date,omitempty"`
	BillingMarketplaceAccount *string `json:"billing_marketplace_account,omitempty"`
	CloudAccountId *string `json:"cloud_account_id,omitempty"`
	CloudProviderId *string `json:"cloud_provider_id,omitempty"`
	ClusterBillingModel *string `json:"cluster_billing_model,omitempty"`
	ClusterId *string `json:"cluster_id,omitempty"`
	ConsoleUrl *string `json:"console_url,omitempty"`
	ConsumerUuid *string `json:"consumer_uuid,omitempty"`
	CpuTotal *int32 `json:"cpu_total,omitempty"`
	CreatorId *string `json:"creator_id,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	ExternalClusterId *string `json:"external_cluster_id,omitempty"`
	// Last time this subscription were reconciled about cluster usage
	LastReconcileDate *time.Time `json:"last_reconcile_date,omitempty"`
	// Last time status was set to Released for this cluster/subscription in Unix time
	LastReleasedAt *time.Time `json:"last_released_at,omitempty"`
	// Last telemetry authorization request for this cluster/subscription in Unix time
	LastTelemetryDate *time.Time `json:"last_telemetry_date,omitempty"`
	Managed bool `json:"managed"`
	OrganizationId *string `json:"organization_id,omitempty"`
	PlanId *string `json:"plan_id,omitempty"`
	ProductBundle *string `json:"product_bundle,omitempty"`
	Provenance *string `json:"provenance,omitempty"`
	RegionId *string `json:"region_id,omitempty"`
	Released *bool `json:"released,omitempty"`
	ServiceLevel *string `json:"service_level,omitempty"`
	SocketTotal *int32 `json:"socket_total,omitempty"`
	Status *string `json:"status,omitempty"`
	SupportLevel *string `json:"support_level,omitempty"`
	SystemUnits *string `json:"system_units,omitempty"`
	// If the subscription is a trial, date the trial ends
	TrialEndDate *time.Time `json:"trial_end_date,omitempty"`
	Usage *string `json:"usage,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Metrics *string `json:"metrics,omitempty"`
	QueryTimestamp *time.Time `json:"query_timestamp,omitempty"`
}

// NewDeletedSubscription instantiates a new DeletedSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedSubscription(managed bool) *DeletedSubscription {
	this := DeletedSubscription{}
	this.Managed = managed
	return &this
}

// NewDeletedSubscriptionWithDefaults instantiates a new DeletedSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedSubscriptionWithDefaults() *DeletedSubscription {
	this := DeletedSubscription{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *DeletedSubscription) GetHref() string {
	if o == nil || isNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetHrefOk() (*string, bool) {
	if o == nil || isNil(o.Href) {
    return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *DeletedSubscription) HasHref() bool {
	if o != nil && !isNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *DeletedSubscription) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeletedSubscription) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeletedSubscription) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *DeletedSubscription) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
    return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *DeletedSubscription) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *DeletedSubscription) SetKind(v string) {
	o.Kind = &v
}

// GetBillingExpirationDate returns the BillingExpirationDate field value if set, zero value otherwise.
func (o *DeletedSubscription) GetBillingExpirationDate() time.Time {
	if o == nil || isNil(o.BillingExpirationDate) {
		var ret time.Time
		return ret
	}
	return *o.BillingExpirationDate
}

// GetBillingExpirationDateOk returns a tuple with the BillingExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetBillingExpirationDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.BillingExpirationDate) {
    return nil, false
	}
	return o.BillingExpirationDate, true
}

// HasBillingExpirationDate returns a boolean if a field has been set.
func (o *DeletedSubscription) HasBillingExpirationDate() bool {
	if o != nil && !isNil(o.BillingExpirationDate) {
		return true
	}

	return false
}

// SetBillingExpirationDate gets a reference to the given time.Time and assigns it to the BillingExpirationDate field.
func (o *DeletedSubscription) SetBillingExpirationDate(v time.Time) {
	o.BillingExpirationDate = &v
}

// GetBillingMarketplaceAccount returns the BillingMarketplaceAccount field value if set, zero value otherwise.
func (o *DeletedSubscription) GetBillingMarketplaceAccount() string {
	if o == nil || isNil(o.BillingMarketplaceAccount) {
		var ret string
		return ret
	}
	return *o.BillingMarketplaceAccount
}

// GetBillingMarketplaceAccountOk returns a tuple with the BillingMarketplaceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetBillingMarketplaceAccountOk() (*string, bool) {
	if o == nil || isNil(o.BillingMarketplaceAccount) {
    return nil, false
	}
	return o.BillingMarketplaceAccount, true
}

// HasBillingMarketplaceAccount returns a boolean if a field has been set.
func (o *DeletedSubscription) HasBillingMarketplaceAccount() bool {
	if o != nil && !isNil(o.BillingMarketplaceAccount) {
		return true
	}

	return false
}

// SetBillingMarketplaceAccount gets a reference to the given string and assigns it to the BillingMarketplaceAccount field.
func (o *DeletedSubscription) SetBillingMarketplaceAccount(v string) {
	o.BillingMarketplaceAccount = &v
}

// GetCloudAccountId returns the CloudAccountId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetCloudAccountId() string {
	if o == nil || isNil(o.CloudAccountId) {
		var ret string
		return ret
	}
	return *o.CloudAccountId
}

// GetCloudAccountIdOk returns a tuple with the CloudAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetCloudAccountIdOk() (*string, bool) {
	if o == nil || isNil(o.CloudAccountId) {
    return nil, false
	}
	return o.CloudAccountId, true
}

// HasCloudAccountId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasCloudAccountId() bool {
	if o != nil && !isNil(o.CloudAccountId) {
		return true
	}

	return false
}

// SetCloudAccountId gets a reference to the given string and assigns it to the CloudAccountId field.
func (o *DeletedSubscription) SetCloudAccountId(v string) {
	o.CloudAccountId = &v
}

// GetCloudProviderId returns the CloudProviderId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetCloudProviderId() string {
	if o == nil || isNil(o.CloudProviderId) {
		var ret string
		return ret
	}
	return *o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetCloudProviderIdOk() (*string, bool) {
	if o == nil || isNil(o.CloudProviderId) {
    return nil, false
	}
	return o.CloudProviderId, true
}

// HasCloudProviderId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasCloudProviderId() bool {
	if o != nil && !isNil(o.CloudProviderId) {
		return true
	}

	return false
}

// SetCloudProviderId gets a reference to the given string and assigns it to the CloudProviderId field.
func (o *DeletedSubscription) SetCloudProviderId(v string) {
	o.CloudProviderId = &v
}

// GetClusterBillingModel returns the ClusterBillingModel field value if set, zero value otherwise.
func (o *DeletedSubscription) GetClusterBillingModel() string {
	if o == nil || isNil(o.ClusterBillingModel) {
		var ret string
		return ret
	}
	return *o.ClusterBillingModel
}

// GetClusterBillingModelOk returns a tuple with the ClusterBillingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetClusterBillingModelOk() (*string, bool) {
	if o == nil || isNil(o.ClusterBillingModel) {
    return nil, false
	}
	return o.ClusterBillingModel, true
}

// HasClusterBillingModel returns a boolean if a field has been set.
func (o *DeletedSubscription) HasClusterBillingModel() bool {
	if o != nil && !isNil(o.ClusterBillingModel) {
		return true
	}

	return false
}

// SetClusterBillingModel gets a reference to the given string and assigns it to the ClusterBillingModel field.
func (o *DeletedSubscription) SetClusterBillingModel(v string) {
	o.ClusterBillingModel = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetClusterId() string {
	if o == nil || isNil(o.ClusterId) {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetClusterIdOk() (*string, bool) {
	if o == nil || isNil(o.ClusterId) {
    return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasClusterId() bool {
	if o != nil && !isNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *DeletedSubscription) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetConsoleUrl returns the ConsoleUrl field value if set, zero value otherwise.
func (o *DeletedSubscription) GetConsoleUrl() string {
	if o == nil || isNil(o.ConsoleUrl) {
		var ret string
		return ret
	}
	return *o.ConsoleUrl
}

// GetConsoleUrlOk returns a tuple with the ConsoleUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetConsoleUrlOk() (*string, bool) {
	if o == nil || isNil(o.ConsoleUrl) {
    return nil, false
	}
	return o.ConsoleUrl, true
}

// HasConsoleUrl returns a boolean if a field has been set.
func (o *DeletedSubscription) HasConsoleUrl() bool {
	if o != nil && !isNil(o.ConsoleUrl) {
		return true
	}

	return false
}

// SetConsoleUrl gets a reference to the given string and assigns it to the ConsoleUrl field.
func (o *DeletedSubscription) SetConsoleUrl(v string) {
	o.ConsoleUrl = &v
}

// GetConsumerUuid returns the ConsumerUuid field value if set, zero value otherwise.
func (o *DeletedSubscription) GetConsumerUuid() string {
	if o == nil || isNil(o.ConsumerUuid) {
		var ret string
		return ret
	}
	return *o.ConsumerUuid
}

// GetConsumerUuidOk returns a tuple with the ConsumerUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetConsumerUuidOk() (*string, bool) {
	if o == nil || isNil(o.ConsumerUuid) {
    return nil, false
	}
	return o.ConsumerUuid, true
}

// HasConsumerUuid returns a boolean if a field has been set.
func (o *DeletedSubscription) HasConsumerUuid() bool {
	if o != nil && !isNil(o.ConsumerUuid) {
		return true
	}

	return false
}

// SetConsumerUuid gets a reference to the given string and assigns it to the ConsumerUuid field.
func (o *DeletedSubscription) SetConsumerUuid(v string) {
	o.ConsumerUuid = &v
}

// GetCpuTotal returns the CpuTotal field value if set, zero value otherwise.
func (o *DeletedSubscription) GetCpuTotal() int32 {
	if o == nil || isNil(o.CpuTotal) {
		var ret int32
		return ret
	}
	return *o.CpuTotal
}

// GetCpuTotalOk returns a tuple with the CpuTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetCpuTotalOk() (*int32, bool) {
	if o == nil || isNil(o.CpuTotal) {
    return nil, false
	}
	return o.CpuTotal, true
}

// HasCpuTotal returns a boolean if a field has been set.
func (o *DeletedSubscription) HasCpuTotal() bool {
	if o != nil && !isNil(o.CpuTotal) {
		return true
	}

	return false
}

// SetCpuTotal gets a reference to the given int32 and assigns it to the CpuTotal field.
func (o *DeletedSubscription) SetCpuTotal(v int32) {
	o.CpuTotal = &v
}

// GetCreatorId returns the CreatorId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetCreatorId() string {
	if o == nil || isNil(o.CreatorId) {
		var ret string
		return ret
	}
	return *o.CreatorId
}

// GetCreatorIdOk returns a tuple with the CreatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetCreatorIdOk() (*string, bool) {
	if o == nil || isNil(o.CreatorId) {
    return nil, false
	}
	return o.CreatorId, true
}

// HasCreatorId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasCreatorId() bool {
	if o != nil && !isNil(o.CreatorId) {
		return true
	}

	return false
}

// SetCreatorId gets a reference to the given string and assigns it to the CreatorId field.
func (o *DeletedSubscription) SetCreatorId(v string) {
	o.CreatorId = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *DeletedSubscription) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetDisplayNameOk() (*string, bool) {
	if o == nil || isNil(o.DisplayName) {
    return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *DeletedSubscription) HasDisplayName() bool {
	if o != nil && !isNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *DeletedSubscription) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetExternalClusterId returns the ExternalClusterId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetExternalClusterId() string {
	if o == nil || isNil(o.ExternalClusterId) {
		var ret string
		return ret
	}
	return *o.ExternalClusterId
}

// GetExternalClusterIdOk returns a tuple with the ExternalClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetExternalClusterIdOk() (*string, bool) {
	if o == nil || isNil(o.ExternalClusterId) {
    return nil, false
	}
	return o.ExternalClusterId, true
}

// HasExternalClusterId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasExternalClusterId() bool {
	if o != nil && !isNil(o.ExternalClusterId) {
		return true
	}

	return false
}

// SetExternalClusterId gets a reference to the given string and assigns it to the ExternalClusterId field.
func (o *DeletedSubscription) SetExternalClusterId(v string) {
	o.ExternalClusterId = &v
}

// GetLastReconcileDate returns the LastReconcileDate field value if set, zero value otherwise.
func (o *DeletedSubscription) GetLastReconcileDate() time.Time {
	if o == nil || isNil(o.LastReconcileDate) {
		var ret time.Time
		return ret
	}
	return *o.LastReconcileDate
}

// GetLastReconcileDateOk returns a tuple with the LastReconcileDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetLastReconcileDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.LastReconcileDate) {
    return nil, false
	}
	return o.LastReconcileDate, true
}

// HasLastReconcileDate returns a boolean if a field has been set.
func (o *DeletedSubscription) HasLastReconcileDate() bool {
	if o != nil && !isNil(o.LastReconcileDate) {
		return true
	}

	return false
}

// SetLastReconcileDate gets a reference to the given time.Time and assigns it to the LastReconcileDate field.
func (o *DeletedSubscription) SetLastReconcileDate(v time.Time) {
	o.LastReconcileDate = &v
}

// GetLastReleasedAt returns the LastReleasedAt field value if set, zero value otherwise.
func (o *DeletedSubscription) GetLastReleasedAt() time.Time {
	if o == nil || isNil(o.LastReleasedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastReleasedAt
}

// GetLastReleasedAtOk returns a tuple with the LastReleasedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetLastReleasedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.LastReleasedAt) {
    return nil, false
	}
	return o.LastReleasedAt, true
}

// HasLastReleasedAt returns a boolean if a field has been set.
func (o *DeletedSubscription) HasLastReleasedAt() bool {
	if o != nil && !isNil(o.LastReleasedAt) {
		return true
	}

	return false
}

// SetLastReleasedAt gets a reference to the given time.Time and assigns it to the LastReleasedAt field.
func (o *DeletedSubscription) SetLastReleasedAt(v time.Time) {
	o.LastReleasedAt = &v
}

// GetLastTelemetryDate returns the LastTelemetryDate field value if set, zero value otherwise.
func (o *DeletedSubscription) GetLastTelemetryDate() time.Time {
	if o == nil || isNil(o.LastTelemetryDate) {
		var ret time.Time
		return ret
	}
	return *o.LastTelemetryDate
}

// GetLastTelemetryDateOk returns a tuple with the LastTelemetryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetLastTelemetryDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.LastTelemetryDate) {
    return nil, false
	}
	return o.LastTelemetryDate, true
}

// HasLastTelemetryDate returns a boolean if a field has been set.
func (o *DeletedSubscription) HasLastTelemetryDate() bool {
	if o != nil && !isNil(o.LastTelemetryDate) {
		return true
	}

	return false
}

// SetLastTelemetryDate gets a reference to the given time.Time and assigns it to the LastTelemetryDate field.
func (o *DeletedSubscription) SetLastTelemetryDate(v time.Time) {
	o.LastTelemetryDate = &v
}

// GetManaged returns the Managed field value
func (o *DeletedSubscription) GetManaged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Managed
}

// GetManagedOk returns a tuple with the Managed field value
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetManagedOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Managed, true
}

// SetManaged sets field value
func (o *DeletedSubscription) SetManaged(v bool) {
	o.Managed = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetOrganizationId() string {
	if o == nil || isNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetOrganizationIdOk() (*string, bool) {
	if o == nil || isNil(o.OrganizationId) {
    return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasOrganizationId() bool {
	if o != nil && !isNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *DeletedSubscription) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetPlanId() string {
	if o == nil || isNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetPlanIdOk() (*string, bool) {
	if o == nil || isNil(o.PlanId) {
    return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasPlanId() bool {
	if o != nil && !isNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *DeletedSubscription) SetPlanId(v string) {
	o.PlanId = &v
}

// GetProductBundle returns the ProductBundle field value if set, zero value otherwise.
func (o *DeletedSubscription) GetProductBundle() string {
	if o == nil || isNil(o.ProductBundle) {
		var ret string
		return ret
	}
	return *o.ProductBundle
}

// GetProductBundleOk returns a tuple with the ProductBundle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetProductBundleOk() (*string, bool) {
	if o == nil || isNil(o.ProductBundle) {
    return nil, false
	}
	return o.ProductBundle, true
}

// HasProductBundle returns a boolean if a field has been set.
func (o *DeletedSubscription) HasProductBundle() bool {
	if o != nil && !isNil(o.ProductBundle) {
		return true
	}

	return false
}

// SetProductBundle gets a reference to the given string and assigns it to the ProductBundle field.
func (o *DeletedSubscription) SetProductBundle(v string) {
	o.ProductBundle = &v
}

// GetProvenance returns the Provenance field value if set, zero value otherwise.
func (o *DeletedSubscription) GetProvenance() string {
	if o == nil || isNil(o.Provenance) {
		var ret string
		return ret
	}
	return *o.Provenance
}

// GetProvenanceOk returns a tuple with the Provenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetProvenanceOk() (*string, bool) {
	if o == nil || isNil(o.Provenance) {
    return nil, false
	}
	return o.Provenance, true
}

// HasProvenance returns a boolean if a field has been set.
func (o *DeletedSubscription) HasProvenance() bool {
	if o != nil && !isNil(o.Provenance) {
		return true
	}

	return false
}

// SetProvenance gets a reference to the given string and assigns it to the Provenance field.
func (o *DeletedSubscription) SetProvenance(v string) {
	o.Provenance = &v
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *DeletedSubscription) GetRegionId() string {
	if o == nil || isNil(o.RegionId) {
		var ret string
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetRegionIdOk() (*string, bool) {
	if o == nil || isNil(o.RegionId) {
    return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *DeletedSubscription) HasRegionId() bool {
	if o != nil && !isNil(o.RegionId) {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given string and assigns it to the RegionId field.
func (o *DeletedSubscription) SetRegionId(v string) {
	o.RegionId = &v
}

// GetReleased returns the Released field value if set, zero value otherwise.
func (o *DeletedSubscription) GetReleased() bool {
	if o == nil || isNil(o.Released) {
		var ret bool
		return ret
	}
	return *o.Released
}

// GetReleasedOk returns a tuple with the Released field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetReleasedOk() (*bool, bool) {
	if o == nil || isNil(o.Released) {
    return nil, false
	}
	return o.Released, true
}

// HasReleased returns a boolean if a field has been set.
func (o *DeletedSubscription) HasReleased() bool {
	if o != nil && !isNil(o.Released) {
		return true
	}

	return false
}

// SetReleased gets a reference to the given bool and assigns it to the Released field.
func (o *DeletedSubscription) SetReleased(v bool) {
	o.Released = &v
}

// GetServiceLevel returns the ServiceLevel field value if set, zero value otherwise.
func (o *DeletedSubscription) GetServiceLevel() string {
	if o == nil || isNil(o.ServiceLevel) {
		var ret string
		return ret
	}
	return *o.ServiceLevel
}

// GetServiceLevelOk returns a tuple with the ServiceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetServiceLevelOk() (*string, bool) {
	if o == nil || isNil(o.ServiceLevel) {
    return nil, false
	}
	return o.ServiceLevel, true
}

// HasServiceLevel returns a boolean if a field has been set.
func (o *DeletedSubscription) HasServiceLevel() bool {
	if o != nil && !isNil(o.ServiceLevel) {
		return true
	}

	return false
}

// SetServiceLevel gets a reference to the given string and assigns it to the ServiceLevel field.
func (o *DeletedSubscription) SetServiceLevel(v string) {
	o.ServiceLevel = &v
}

// GetSocketTotal returns the SocketTotal field value if set, zero value otherwise.
func (o *DeletedSubscription) GetSocketTotal() int32 {
	if o == nil || isNil(o.SocketTotal) {
		var ret int32
		return ret
	}
	return *o.SocketTotal
}

// GetSocketTotalOk returns a tuple with the SocketTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetSocketTotalOk() (*int32, bool) {
	if o == nil || isNil(o.SocketTotal) {
    return nil, false
	}
	return o.SocketTotal, true
}

// HasSocketTotal returns a boolean if a field has been set.
func (o *DeletedSubscription) HasSocketTotal() bool {
	if o != nil && !isNil(o.SocketTotal) {
		return true
	}

	return false
}

// SetSocketTotal gets a reference to the given int32 and assigns it to the SocketTotal field.
func (o *DeletedSubscription) SetSocketTotal(v int32) {
	o.SocketTotal = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeletedSubscription) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeletedSubscription) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeletedSubscription) SetStatus(v string) {
	o.Status = &v
}

// GetSupportLevel returns the SupportLevel field value if set, zero value otherwise.
func (o *DeletedSubscription) GetSupportLevel() string {
	if o == nil || isNil(o.SupportLevel) {
		var ret string
		return ret
	}
	return *o.SupportLevel
}

// GetSupportLevelOk returns a tuple with the SupportLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetSupportLevelOk() (*string, bool) {
	if o == nil || isNil(o.SupportLevel) {
    return nil, false
	}
	return o.SupportLevel, true
}

// HasSupportLevel returns a boolean if a field has been set.
func (o *DeletedSubscription) HasSupportLevel() bool {
	if o != nil && !isNil(o.SupportLevel) {
		return true
	}

	return false
}

// SetSupportLevel gets a reference to the given string and assigns it to the SupportLevel field.
func (o *DeletedSubscription) SetSupportLevel(v string) {
	o.SupportLevel = &v
}

// GetSystemUnits returns the SystemUnits field value if set, zero value otherwise.
func (o *DeletedSubscription) GetSystemUnits() string {
	if o == nil || isNil(o.SystemUnits) {
		var ret string
		return ret
	}
	return *o.SystemUnits
}

// GetSystemUnitsOk returns a tuple with the SystemUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetSystemUnitsOk() (*string, bool) {
	if o == nil || isNil(o.SystemUnits) {
    return nil, false
	}
	return o.SystemUnits, true
}

// HasSystemUnits returns a boolean if a field has been set.
func (o *DeletedSubscription) HasSystemUnits() bool {
	if o != nil && !isNil(o.SystemUnits) {
		return true
	}

	return false
}

// SetSystemUnits gets a reference to the given string and assigns it to the SystemUnits field.
func (o *DeletedSubscription) SetSystemUnits(v string) {
	o.SystemUnits = &v
}

// GetTrialEndDate returns the TrialEndDate field value if set, zero value otherwise.
func (o *DeletedSubscription) GetTrialEndDate() time.Time {
	if o == nil || isNil(o.TrialEndDate) {
		var ret time.Time
		return ret
	}
	return *o.TrialEndDate
}

// GetTrialEndDateOk returns a tuple with the TrialEndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetTrialEndDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.TrialEndDate) {
    return nil, false
	}
	return o.TrialEndDate, true
}

// HasTrialEndDate returns a boolean if a field has been set.
func (o *DeletedSubscription) HasTrialEndDate() bool {
	if o != nil && !isNil(o.TrialEndDate) {
		return true
	}

	return false
}

// SetTrialEndDate gets a reference to the given time.Time and assigns it to the TrialEndDate field.
func (o *DeletedSubscription) SetTrialEndDate(v time.Time) {
	o.TrialEndDate = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *DeletedSubscription) GetUsage() string {
	if o == nil || isNil(o.Usage) {
		var ret string
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetUsageOk() (*string, bool) {
	if o == nil || isNil(o.Usage) {
    return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *DeletedSubscription) HasUsage() bool {
	if o != nil && !isNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given string and assigns it to the Usage field.
func (o *DeletedSubscription) SetUsage(v string) {
	o.Usage = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DeletedSubscription) GetCreatedAt() time.Time {
	if o == nil || isNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DeletedSubscription) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DeletedSubscription) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *DeletedSubscription) GetMetrics() string {
	if o == nil || isNil(o.Metrics) {
		var ret string
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetMetricsOk() (*string, bool) {
	if o == nil || isNil(o.Metrics) {
    return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *DeletedSubscription) HasMetrics() bool {
	if o != nil && !isNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given string and assigns it to the Metrics field.
func (o *DeletedSubscription) SetMetrics(v string) {
	o.Metrics = &v
}

// GetQueryTimestamp returns the QueryTimestamp field value if set, zero value otherwise.
func (o *DeletedSubscription) GetQueryTimestamp() time.Time {
	if o == nil || isNil(o.QueryTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.QueryTimestamp
}

// GetQueryTimestampOk returns a tuple with the QueryTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedSubscription) GetQueryTimestampOk() (*time.Time, bool) {
	if o == nil || isNil(o.QueryTimestamp) {
    return nil, false
	}
	return o.QueryTimestamp, true
}

// HasQueryTimestamp returns a boolean if a field has been set.
func (o *DeletedSubscription) HasQueryTimestamp() bool {
	if o != nil && !isNil(o.QueryTimestamp) {
		return true
	}

	return false
}

// SetQueryTimestamp gets a reference to the given time.Time and assigns it to the QueryTimestamp field.
func (o *DeletedSubscription) SetQueryTimestamp(v time.Time) {
	o.QueryTimestamp = &v
}

func (o DeletedSubscription) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !isNil(o.BillingExpirationDate) {
		toSerialize["billing_expiration_date"] = o.BillingExpirationDate
	}
	if !isNil(o.BillingMarketplaceAccount) {
		toSerialize["billing_marketplace_account"] = o.BillingMarketplaceAccount
	}
	if !isNil(o.CloudAccountId) {
		toSerialize["cloud_account_id"] = o.CloudAccountId
	}
	if !isNil(o.CloudProviderId) {
		toSerialize["cloud_provider_id"] = o.CloudProviderId
	}
	if !isNil(o.ClusterBillingModel) {
		toSerialize["cluster_billing_model"] = o.ClusterBillingModel
	}
	if !isNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !isNil(o.ConsoleUrl) {
		toSerialize["console_url"] = o.ConsoleUrl
	}
	if !isNil(o.ConsumerUuid) {
		toSerialize["consumer_uuid"] = o.ConsumerUuid
	}
	if !isNil(o.CpuTotal) {
		toSerialize["cpu_total"] = o.CpuTotal
	}
	if !isNil(o.CreatorId) {
		toSerialize["creator_id"] = o.CreatorId
	}
	if !isNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !isNil(o.ExternalClusterId) {
		toSerialize["external_cluster_id"] = o.ExternalClusterId
	}
	if !isNil(o.LastReconcileDate) {
		toSerialize["last_reconcile_date"] = o.LastReconcileDate
	}
	if !isNil(o.LastReleasedAt) {
		toSerialize["last_released_at"] = o.LastReleasedAt
	}
	if !isNil(o.LastTelemetryDate) {
		toSerialize["last_telemetry_date"] = o.LastTelemetryDate
	}
	if true {
		toSerialize["managed"] = o.Managed
	}
	if !isNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !isNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !isNil(o.ProductBundle) {
		toSerialize["product_bundle"] = o.ProductBundle
	}
	if !isNil(o.Provenance) {
		toSerialize["provenance"] = o.Provenance
	}
	if !isNil(o.RegionId) {
		toSerialize["region_id"] = o.RegionId
	}
	if !isNil(o.Released) {
		toSerialize["released"] = o.Released
	}
	if !isNil(o.ServiceLevel) {
		toSerialize["service_level"] = o.ServiceLevel
	}
	if !isNil(o.SocketTotal) {
		toSerialize["socket_total"] = o.SocketTotal
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.SupportLevel) {
		toSerialize["support_level"] = o.SupportLevel
	}
	if !isNil(o.SystemUnits) {
		toSerialize["system_units"] = o.SystemUnits
	}
	if !isNil(o.TrialEndDate) {
		toSerialize["trial_end_date"] = o.TrialEndDate
	}
	if !isNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !isNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !isNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !isNil(o.QueryTimestamp) {
		toSerialize["query_timestamp"] = o.QueryTimestamp
	}
	return json.Marshal(toSerialize)
}

type NullableDeletedSubscription struct {
	value *DeletedSubscription
	isSet bool
}

func (v NullableDeletedSubscription) Get() *DeletedSubscription {
	return v.value
}

func (v *NullableDeletedSubscription) Set(val *DeletedSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedSubscription(val *DeletedSubscription) *NullableDeletedSubscription {
	return &NullableDeletedSubscription{value: val, isSet: true}
}

func (v NullableDeletedSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


