"""
    Service Registry Management API

    Service Registry Management API is a REST API for managing Service Registry instances. Service Registry is a datastore for event schemas and API designs, which is based on the open source Apicurio Registry project.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: rhosak-eval-support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_service_registry_mgmt_sdk
from rhoas_service_registry_mgmt_sdk.model.error_all_of import ErrorAllOf


class TestErrorAllOf(unittest.TestCase):
    """ErrorAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorAllOf(self):
        """Test ErrorAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
