/*
 * sso.redhat.com API documentation
 * This is the API documentation for sso.redhat.com
 *
 * The version of the OpenAPI document: 5.0.19-SNAPSHOT
 * Contact: it-user-team-list@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.serviceaccounts.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openshift.cloud.api.serviceaccounts.models.AuthenticationFactors;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthenticationPolicy
 */
@JsonPropertyOrder({
  AuthenticationPolicy.JSON_PROPERTY_AUTHENTICATION_FACTORS
})
@JsonTypeName("AuthenticationPolicy")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuthenticationPolicy {
  public static final String JSON_PROPERTY_AUTHENTICATION_FACTORS = "authenticationFactors";
  private AuthenticationFactors authenticationFactors;

  public AuthenticationPolicy() { 
  }

  public AuthenticationPolicy authenticationFactors(AuthenticationFactors authenticationFactors) {
    
    this.authenticationFactors = authenticationFactors;
    return this;
  }

   /**
   * Get authenticationFactors
   * @return authenticationFactors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_FACTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuthenticationFactors getAuthenticationFactors() {
    return authenticationFactors;
  }


  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_FACTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticationFactors(AuthenticationFactors authenticationFactors) {
    this.authenticationFactors = authenticationFactors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationPolicy authenticationPolicy = (AuthenticationPolicy) o;
    return Objects.equals(this.authenticationFactors, authenticationPolicy.authenticationFactors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationFactors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationPolicy {\n");
    sb.append("    authenticationFactors: ").append(toIndentedString(authenticationFactors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

