"""
    sso.redhat.com API documentation

    This is the API documentation for sso.redhat.com  # noqa: E501

    The version of the OpenAPI document: 5.0.19-SNAPSHOT
    Contact: it-user-team-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rhoas_service_accounts_mgmt_sdk
from rhoas_service_accounts_mgmt_sdk.model.otp import Otp


class TestOtp(unittest.TestCase):
    """Otp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtp(self):
        """Test Otp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Otp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
