/*
Kafka Instance API

Testing TopicsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kafkainstanceclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_kafkainstanceclient_TopicsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test TopicsApiService CreateTopic", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.TopicsApi.CreateTopic(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test TopicsApiService DeleteTopic", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var topicName string

        resp, httpRes, err := apiClient.TopicsApi.DeleteTopic(context.Background(), topicName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test TopicsApiService GetTopic", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var topicName string

        resp, httpRes, err := apiClient.TopicsApi.GetTopic(context.Background(), topicName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test TopicsApiService GetTopics", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.TopicsApi.GetTopics(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test TopicsApiService UpdateTopic", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var topicName string

        resp, httpRes, err := apiClient.TopicsApi.UpdateTopic(context.Background(), topicName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
