/*
Kafka Instance API

Testing RecordsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kafkainstanceclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_kafkainstanceclient_RecordsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test RecordsApiService ConsumeRecords", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var topicName string

        resp, httpRes, err := apiClient.RecordsApi.ConsumeRecords(context.Background(), topicName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test RecordsApiService ProduceRecord", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var topicName string

        resp, httpRes, err := apiClient.RecordsApi.ProduceRecord(context.Background(), topicName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
