/*
Kafka Instance API

Testing GroupsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kafkainstanceclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_kafkainstanceclient_GroupsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test GroupsApiService DeleteConsumerGroupById", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var consumerGroupId string

        resp, httpRes, err := apiClient.GroupsApi.DeleteConsumerGroupById(context.Background(), consumerGroupId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test GroupsApiService GetConsumerGroupById", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var consumerGroupId string

        resp, httpRes, err := apiClient.GroupsApi.GetConsumerGroupById(context.Background(), consumerGroupId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test GroupsApiService GetConsumerGroups", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.GroupsApi.GetConsumerGroups(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test GroupsApiService ResetConsumerGroupOffset", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var consumerGroupId string

        resp, httpRes, err := apiClient.GroupsApi.ResetConsumerGroupOffset(context.Background(), consumerGroupId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
