/*
 * Service Registry API
 * Service Registry Instance API  NOTE: This API cannot be called directly from the portal.
 *
 * The version of the OpenAPI document: 2.2.5.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.registry.instance.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openshift.cloud.api.registry.instance.models.RuleViolationCause;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RuleViolationErrorAllOf
 */
@JsonPropertyOrder({
  RuleViolationErrorAllOf.JSON_PROPERTY_CAUSES
})
@JsonTypeName("RuleViolationError_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RuleViolationErrorAllOf {
  public static final String JSON_PROPERTY_CAUSES = "causes";
  private List<RuleViolationCause> causes = new ArrayList<>();

  public RuleViolationErrorAllOf() { 
  }

  public RuleViolationErrorAllOf causes(List<RuleViolationCause> causes) {
    
    this.causes = causes;
    return this;
  }

  public RuleViolationErrorAllOf addCausesItem(RuleViolationCause causesItem) {
    this.causes.add(causesItem);
    return this;
  }

   /**
   * List of rule violation causes.
   * @return causes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of rule violation causes.")
  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RuleViolationCause> getCauses() {
    return causes;
  }


  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCauses(List<RuleViolationCause> causes) {
    this.causes = causes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleViolationErrorAllOf ruleViolationErrorAllOf = (RuleViolationErrorAllOf) o;
    return Objects.equals(this.causes, ruleViolationErrorAllOf.causes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(causes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleViolationErrorAllOf {\n");
    sb.append("    causes: ").append(toIndentedString(causes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

